import 'dart:math';

class StoicQuotes {
  static final List<String> quotes = [
    "The obstacle is the way. - Marcus Aurelius",
    "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "Waste no more time arguing what a good man should be. Be one. - Marcus Aurelius",
    "First say to yourself what you would be; then do what you have to do. - Epictetus",
    "It's not what happens to you, but how you react to it that matters. - Epictetus",
    "We suffer more in imagination than in reality. - Seneca",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
    "If it is not right, do not do it, if it is not true, do not say it. - Marcus Aurelius",
    "He who fears death will never do anything worthy of a living man. - Seneca",
    "No person has the power to have everything they want, but it is in their power not to want what they don't have. - Seneca",
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "You become what you give your attention to. - Epictetus",
    "If you want to improve, be content to be thought foolish and stupid. - Epictetus",
    "The key is to keep company only with people who uplift you, whose presence calls forth your best. - Epictetus",
    "He who is brave is free. - Seneca",
    "Difficulties strengthen the mind, as labor does the body. - Seneca",
    "The mind adapts and converts to its own purposes the obstacle to our acting. - Marcus Aurelius",
    "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
    "Waste no more time arguing what a good man should be. Be one. - Marcus Aurelius",
    "First say to yourself what you would be; then do what you have to do. - Epictetus",
    "It's not what happens to you, but how you react to it that matters. - Epictetus",
    "We suffer more in imagination than in reality. - Seneca",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "The best revenge is to be unlike him who performed the injury. - Marcus Aurelius",
    "If it is not right, do not do it, if it is not true, do not say it. - Marcus Aurelius",
    "He who fears death will never do anything worthy of a living man. - Seneca",
    "No person has the power to have everything they want, but it is in their power not to want what they don't have. - Seneca",
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "No person has the power to have everything they want, but it is in their power not to want what they don't have. - Seneca",
    "The happiness of your life depends upon the quality of your thoughts. - Marcus Aurelius",
    "He who fears death will never do anything worth of a man who is alive. - Seneca",
    "It is not what happens to you, but how you react to it that matters. - Epictetus",
    "Luck is what happens when preparation meets opportunity. - Seneca",
    "Dwell on the beauty of life. Watch the stars, and see yourself running with them. - Marcus Aurelius",
    "First say to yourself what you would be; and then do what you have to do. - Epictetus",
    "Man conquers the world by conquering himself. - Zeno of Citium",
    "The more we value things outside our control, the less control we have. - Epictetus",
    "Don't explain your philosophy. Embody it. - Epictetus",
    "Sometimes even to live is an act of courage. - Seneca",
    "You have power over your mind - not outside events. Realize this, and you will find strength. - Marcus Aurelius",
    "The best revenge is not to be like your enemy. - Marcus Aurelius",
    "Begin at once to live, and count each separate day as a separate life. - Seneca",
    "How long are you going to wait before you demand the best for yourself? - Epictetus",
    "We suffer more in imagination than in reality. - Seneca",
    "No man is free who is not master of himself. - Epictetus",
    "If it is not right, do not do it; if it is not true, do not say it. - Marcus Aurelius",
    "The whole future lies in uncertainty: live immediately. - Seneca",
    "Make the best use of what is in your power, and take the rest as it happens. - Epictetus",
    "It is not the man who has too little, but the man who craves more, that is poor. - Seneca",
    "To improve is to change; to be perfect is to change often. - Winston Churchill",
    "Success is not final, failure is not fatal: It is the courage to continue that counts. - Winston Churchill",
    "Action is the foundational key to all success. - Pablo Picasso",
    "Success usually comes to those who are too busy to be looking for it. - Henry David Thoreau",
    "Don’t be afraid to give up the good to go for the great. - John D. Rockefeller",
    "I find that the harder I work, the more luck I seem to have. - Thomas Jefferson",
    "Success is not in what you have, but who you are. - Bo Bennett",
    "If you really want to do something, you'll find a way. If you don't, you'll find an excuse. - Jim Rohn",
    "Success seems to be connected with action. Successful people keep moving. - Conrad Hilton",
    "The secret of success is to do the common thing uncommonly well. - John D. Rockefeller Jr.",
    "Don’t wish it were easier; wish you were better. - Jim Rohn",
    "All progress takes place outside the comfort zone. - Michael John Bobak",
    "Success is the sum of small efforts, repeated day-in and day-out. - Robert Collier",
    "If you want to achieve greatness stop asking for permission. - Anonymous",
    "Things work out best for those who make the best of how things work out. - John Wooden",
    "To live a fulfilled life, we need to keep creating the “what is next,” of our lives. Without dreams and goals, there is no living, only merely existing, and that is not why we are here. - Mark Twain",
    "Success is walking from failure to failure with no loss of enthusiasm. - Winston Churchill",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "The only place where success comes before work is in the dictionary. - Vidal Sassoon",
    "Fall seven times and stand up eight. - Japanese Proverb",
    "Do one thing every day that scares you. - Eleanor Roosevelt",
    "The way to get started is to quit talking and begin doing. - Walt Disney",
    "Dream big and dare to fail. - Norman Vaughan",
    "Do not wait to strike till the iron is hot, but make it hot by striking. - William Butler Yeats",
    "Whether you think you can or you think you can’t, you’re right. - Henry Ford",
    "Everything you’ve ever wanted is on the other side of fear. - George Addair",
    "Success is not how high you have climbed, but how you make a positive difference to the world. - Roy T. Bennett",
    "The best way to predict the future is to create it. - Peter Drucker",
    "Hardships often prepare ordinary people for an extraordinary destiny. - C.S. Lewis",
    "The road to success and the road to failure are almost exactly the same. - Colin R. Davis",
    "Don’t let the fear of losing be greater than the excitement of winning. - Robert Kiyosaki",
    "If you genuinely want something, don’t wait for it – teach yourself to be impatient. - Gurbaksh Chahal",
    "The only limit to our realization of tomorrow will be our doubts of today. - Franklin D. Roosevelt",
    "Don’t let what you cannot do interfere with what you can do. - John Wooden",
    "People who are crazy enough to think they can change the world, are the ones who do. - Rob Siltanen",
    "Opportunities don’t happen. You create them. - Chris Grosser",
    "Success is not the key to happiness. Happiness is the key to success. If you love what you are doing, you will be successful. - Albert Schweitzer",
    "Don’t wait. The time will never be just right. - Napoleon Hill",
    "It’s not whether you get knocked down, it’s whether you get up. - Vince Lombardi",
    "Never give in except to convictions of honor and good sense. - Winston Churchill",
    "Stop chasing the money and start chasing the passion. - Tony Hsieh",
    "Success is how high you bounce when you hit bottom. - George S. Patton",
    "Success is not the absence of failure; it’s the persistence through failure. - Aisha Tyler",
    "Courage is resistance to fear, mastery of fear—not absence of fear. - Mark Twain",
    "The successful warrior is the average man, with laser-like focus. - Bruce Lee",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Do not be embarrassed by your failures, learn from them and start again. - Richard Branson",
    "Success is not just making money. Success is happiness. Success is fulfillment; it’s the ability to give. - Adam Neumann",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Success is a journey, not a destination. - Arthur Ashe",
    "The question isn’t who is going to let me; it’s who is going to stop me. - Ayn Rand",
    "Success is not about never falling, but about rising every time you fall. - Nelson Mandela",
    "Effort only fully releases its reward after a person refuses to quit. - Napoleon Hill",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "Do what you feel in your heart to be right—for you’ll be criticized anyway. - Eleanor Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Do not be embarrassed by your failures, learn from them and start again. - Richard Branson",
    "Success is not just making money. Success is happiness. Success is fulfillment; it’s the ability to give. - Adam Neumann",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "Start where you are. Use what you have. Do what you can. - Arthur Ashe",
    "Success is a journey, not a destination. - Arthur Ashe",
    "The question isn’t who is going to let me; it’s who is going to stop me. - Ayn Rand",
    "Success is not about never falling, but about rising every time you fall. - Nelson Mandela",
    "Effort only fully releases its reward after a person refuses to quit. - Napoleon Hill",
    "You don’t have to be great to start, but you have to start to be great. - Zig Ziglar",
    "Success is liking yourself, liking what you do, and liking how you do it. - Maya Angelou",
    "It does not matter how slowly you go as long as you do not stop. - Confucius",
    "Keep your face always toward the sunshine—and shadows will fall behind you. - Walt Whitman",
    "Go confidently in the direction of your dreams. Live the life you have imagined. - Henry David Thoreau",
    "Do what you feel in your heart to be right—for you’ll be criticized anyway. - Eleanor Roosevelt",
    "The only way to do great work is to love what you do. - Steve Jobs",
    "Don’t be pushed around by the fears in your mind. Be led by the dreams in your heart. - Roy T. Bennett",
    "The future belongs to those who believe in the beauty of their dreams. - Eleanor Roosevelt",
    "Do not be embarrassed by your failures, learn from them and start again. - Richard Branson",
    "Success is not just making money. Success is happiness. Success is fulfillment; it’s the ability to give. - Adam Neumann",
    "The only way to achieve the impossible is to believe it is possible. - Charles Kingsleigh",
    "The obstacle is the way. - Marcus Aurelius",
    "Do not act as if you are going to live 10,000 years. Death hangs over you. While you live, while it is in your power, be good. - Marcus Aurelius",
    "Wealth consists not in having great possessions, but in having few wants. - Epictetus",
    "A gem cannot be polished without friction, nor a man perfected without trials. - Seneca",
    "Difficulty shows what men are. - Epictetus",
    "The greater the difficulty, the more glory in surmounting it. - Epicurus",
    "He who has a why to live can bear almost any how. - Friedrich Nietzsche",
    "To bear trials with a calm mind robs misfortune of its strength and burden. - Seneca",
    "If you are pained by external things, it is not they that disturb you, but your own judgment of them. And it is in your power to wipe out that judgment now. - Marcus Aurelius",
    "Freedom is the only worthy goal in life. It is won by disregarding things that lie beyond our control. - Epictetus",
    "Don’t seek for everything to happen as you wish it would, but rather wish that everything happens as it actually will—then your life will flow well. - Epictetus",
    "Fate leads the willing, and drags along the reluctant. - Seneca",
    "Anger, if not restrained, is frequently more hurtful to us than the injury that provokes it. - Seneca",
    "The universe is change; our life is what our thoughts make it. - Marcus Aurelius",
    "Attach yourself to what is spiritually superior, regardless of what other people think or do. Hold to your true aspirations no matter what is going on around you. - Epictetus",
    "True happiness is to enjoy the present, without anxious dependence upon the future. - Seneca",
    "To love only what happens, what was destined. No greater harmony. - Marcus Aurelius",
    "You are the architect of your own destiny. - Epictetus",
    "Control thy passions lest they take vengeance on thee. - Epictetus",
    "It is the power of the mind to be unconquerable. - Seneca",
    "Success is to be measured not so much by the position that one has reached in life as by the obstacles which he has overcome. - Booker T. Washington",
    "Believe you can and you’re halfway there. - Theodore Roosevelt",
    "Hard work beats talent when talent doesn’t work hard. - Tim Notke",
    "Do not be afraid of growing slowly, be afraid only of standing still. - Chinese Proverb",
    "The best way to succeed in life is to act on the advice you give to others. - Anonymous",
    "Don’t stop when you’re tired. Stop when you’re done. - Marilyn Monroe",
    "The key to success is to focus our conscious mind on things we desire, not things we fear. - Brian Tracy",
    "Success is achieved and maintained by those who try and keep trying. - W. Clement Stone",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Success is falling nine times and getting up ten. - Jon Bon Jovi",
    "You may have to fight a battle more than once to win it. - Margaret Thatcher",
    "If you don’t value your time, neither will others. Stop giving away your time and talents—start charging for it. - Kim Garst",
    "Success isn’t just about what you accomplish in your life; it’s about what you inspire others to do. - Anonymous",
    "Do not wait for the perfect moment. Take the moment and make it perfect. - Anonymous",
    "The only limit to your impact is your imagination and commitment. - Tony Robbins",
    "Discipline is the bridge between goals and accomplishment. - Jim Rohn",
    "Your limitation—it’s only your imagination. - Anonymous",
    "Dream bigger. Do bigger. - Anonymous",
    "Push yourself, because no one else is going to do it for you. - Anonymous",
    "Great things never come from comfort zones. - Anonymous",
    "The harder you work for something, the greater you’ll feel when you achieve it. - Anonymous",
    "Success doesn’t come from what you do occasionally, it comes from what you do consistently. - Anonymous",
    "Work hard in silence. Let success be your noise. - Frank Ocean",
    "Don’t watch the clock; do what it does. Keep going. - Sam Levenson",
    "Opportunities are usually disguised as hard work, so most people don’t recognize them. - Ann Landers",
    "Do not let what you cannot do interfere with what you can do. - John Wooden",
    "Chase your dreams until you catch them. - Anonymous",
    "Success is not a destination, it’s a journey. - Zig Ziglar",
    "Stay positive, work hard, make it happen. - Anonymous",
    "Big journeys begin with small steps. - Anonymous",
    "Every champion was once a contender that didn’t give up. - Gabby Douglas",
    "Focus on your goal. Don’t look in any direction but ahead. - Anonymous",
    "Set your goals high, and don’t stop till you get there. - Bo Jackson",
    "Go the extra mile. It’s never crowded. - Wayne Dyer",
    "Success is a state of mind. If you want success, start thinking of yourself as a success. - Joyce Brothers",
    "The only person you should try to be better than is the person you were yesterday. - Anonymous",
    "The secret of getting ahead is getting started. - Mark Twain",
    "Don’t let small minds convince you that your dreams are too big. - Anonymous",
    "It’s not about ideas. It’s about making ideas happen. - Scott Belsky",
    "The harder you work, the luckier you get. - Gary Player",
    "Don’t stop until you’re proud. - Anonymous",
    "You don’t get what you wish for. You get what you work for. - Anonymous",
    "Be so good they can’t ignore you. - Steve Martin",
    "Failure is not the opposite of success; it’s part of success. - Arianna Huffington",
    "Dream it. Wish it. Do it. - Anonymous",
    "Wake up with determination. Go to bed with satisfaction. - Anonymous",
    "Don’t count the days, make the days count. - Muhammad Ali",
    "Success is not the key to happiness. Happiness is the key to success. - Albert Schweitzer",
    "The expert in anything was once a beginner. - Helen Hayes",
    "Little things make big days. - Anonymous",
    "It always seems impossible until it’s done. - Nelson Mandela",
    "Do what you can with all you have, wherever you are. - Theodore Roosevelt",
    "The man who has confidence in himself gains the confidence of others. - Hasidic Proverb",
    "Don’t wait for opportunity. Create it. - Anonymous",
    "Opportunities don’t happen. You create them. - Chris Grosser",
    "Your time is limited, so don’t waste it living someone else’s life. - Steve Jobs",
    "The secret to success is to know something nobody else knows. - Aristotle Onassis",
    "Fall seven times, stand up eight. - Japanese Proverb",
    "Be fearless in the pursuit of what sets your soul on fire. - Anonymous",
    "Do something today that your future self will thank you for. - Sean Patrick Flanery",
    "Hard times don’t create heroes. It is during the hard times when the ‘hero’ within us is revealed. - Bob Riley",
  ];

  static String getRandomQuote() {
    final random = Random();
    return quotes[random.nextInt(quotes.length)];
  }
}
